import {
  LayoutDashboard,
  Users,
  User,
  UserSquare2,
  BookOpen,
  Building2,
  Calendar,
  CalendarCheck,
  CreditCard,
  ClipboardCheck,
  GraduationCap,
  Settings,
  Shield,
  MessageSquare,
  HelpCircle,
  Home,
  Bus,
  BookOpenCheck,
  Package,
  FileCheck,
  TrendingUp,
  BarChart2,
  Warehouse,
  CalendarDays,
  GitBranch,
  CalendarClock,
  ArrowRightLeft,
  FileSpreadsheet,
  Landmark,
  Bell,
  Megaphone,
  PartyPopper,
  FileText,
  Award,
  IdCard,
  UserPlus,
  Building,
  Wrench,
  Tag,
  Receipt,
  DollarSign,
  FileBarChart,
  FolderOpen,
  Ticket,
  ShieldCheck,
  Lock,
  Heart,
  Briefcase,
  BookMarked,
  FlaskConical,
  UserCheck,
  DoorOpen,
  Coins,
  ShoppingCart,
  Lightbulb,
  Boxes,
  Activity,
  Workflow,
  Cpu,
  Brain,
  LineChart,
  ShieldAlert,
  Network,
  Database,
  Paintbrush,
  Settings2,
  CheckSquare,
  MessageCircle,
  ThumbsUp,
  AlertTriangle,
  Book,
  Video,
  AlertOctagon,
  FolderTree,
  ChartBar,
  PieChart,
  Clock8,
  Banknote,
  Fuel,
  Truck,
  BedDouble,
  Key,
  DatabaseBackup,
  School,
  UserCog,
  ClipboardList,
  Zap,
  Globe,
} from 'lucide-react';

export const SCHOOL_NAVIGATION = [
  {
    title: null,
    items: [
      {
        title: 'Dashboard',
        href: '/dashboard',
        icon: LayoutDashboard,
      },
    ],
  },
  {
    title: 'Academic Management',
    items: [
      {
        title: 'Students',
        href: '/dashboard/students',
        icon: Users,
        permission: 'students.view',
        feature: 'students',
      },
      {
        title: 'Admissions',
        href: '/dashboard/admissions',
        icon: UserPlus,
        permission: 'students.view',
        feature: 'admissions',
      },
      {
        title: 'Teachers',
        href: '/dashboard/teachers',
        icon: UserSquare2,
        permission: 'teachers.view',
        feature: 'teachers',
      },
      {
        title: 'Departments',
        href: '/dashboard/departments',
        icon: Building2,
        permission: 'teachers.view',
        feature: 'departments',
      },
      {
        title: 'Designations',
        href: '/dashboard/designations',
        icon: Briefcase,
        permission: 'teachers.view',
        feature: 'designations',
      },
      {
        title: 'Parents',
        href: '/dashboard/parents',
        icon: Users,
        permission: 'students.view',
        feature: 'parents',
      },
      {
        title: 'Classes',
        href: '/dashboard/classes',
        icon: BookOpen,
        permission: 'classes.view',
        feature: 'classes',
      },
      {
        title: 'Subjects',
        href: '/dashboard/subjects',
        icon: BookOpen,
        permission: 'subjects.view',
        feature: 'subjects',
      },
      {
        title: 'Curriculum',
        href: '/dashboard/curriculum',
        icon: BookMarked,
        permission: 'subjects.view',
        feature: 'curriculum',
      },
      {
        title: 'Schedule',
        href: '/dashboard/schedule',
        icon: CalendarClock,
        permission: 'classes.view',
      },
      {
        title: 'Automatic Timetabling',
        href: '/dashboard/automatic-timetabling',
        icon: Clock8,
        permission: 'classes.view',
        feature: 'automatic-timetabling',
      },
      {
        title: 'Attendance',
        href: '/dashboard/attendance',
        icon: ClipboardCheck,
        permission: 'attendance.view',
        feature: 'attendance',
      },
      {
        title: 'Homework',
        href: '/dashboard/homework',
        icon: FileText,
        permission: 'students.view',
        feature: 'homework',
      },
      {
        title: 'Lesson Plans',
        href: '/dashboard/lesson-plans',
        icon: FileSpreadsheet,
        permission: 'teachers.view',
        feature: 'lesson-plans',
      },
    ],
  },
  {
    title: 'Examinations',
    items: [
      {
        title: 'Exams',
        href: '/dashboard/exams',
        icon: GraduationCap,
        permission: 'exams.view',
        feature: 'exams',
      },
      {
        title: 'Online Exams',
        href: '/dashboard/online-exams',
        icon: FlaskConical,
        permission: 'exams.view',
        feature: 'online-exams',
      },
      {
        title: 'Question Banks',
        href: '/dashboard/question-banks',
        icon: FolderTree,
        permission: 'exams.view',
        feature: 'question-banks',
      },
      {
        title: 'Questions',
        href: '/dashboard/questions',
        icon: HelpCircle,
        permission: 'exams.view',
        feature: 'question-banks',
      },
      {
        title: 'Exam Results',
        href: '/dashboard/exam-results',
        icon: Award,
        permission: 'exams.view',
      },
      {
        title: 'Exam Halls',
        href: '/dashboard/exam-halls',
        icon: DoorOpen,
        permission: 'exams.view',
      },
      {
        title: 'Promotions',
        href: '/dashboard/promotions',
        icon: ArrowRightLeft,
        permission: 'students.view',
      },
      {
        title: 'Certificates',
        href: '/dashboard/certificates',
        icon: Award,
        permission: 'exams.view',
        feature: 'certificates',
      },
      {
        title: 'ID Cards',
        href: '/dashboard/id-cards',
        icon: IdCard,
        permission: 'students.view',
        feature: 'id-cards',
      },
      {
        title: 'Portfolios',
        href: '/dashboard/portfolios',
        icon: FolderOpen,
        permission: 'students.view',
        feature: 'portfolios',
      },
      {
        title: 'Delivery Reports',
        href: '/dashboard/delivery-reports',
        icon: FileBarChart,
        permission: 'exams.view',
        feature: 'delivery-reports',
      },
    ],
  },
  {
    title: 'Student Welfare',
    items: [
      {
        title: 'Discipline',
        href: '/dashboard/discipline',
        icon: ShieldAlert,
        permission: 'students.view',
        feature: 'discipline',
      },
      {
        title: 'Health Records',
        href: '/dashboard/health-records',
        icon: Heart,
        permission: 'students.view',
        feature: 'health',
      },
      {
        title: 'Alumni',
        href: '/dashboard/alumni',
        icon: GraduationCap,
        permission: 'students.view',
        feature: 'alumni',
      },
      {
        title: 'Visitors',
        href: '/dashboard/visitors',
        icon: UserCheck,
        permission: 'settings.view',
        feature: 'visitors',
      },
    ],
  },
  {
    title: 'Finance',
    items: [
      {
        title: 'Finance',
        href: '/dashboard/payments',
        icon: CreditCard,
        permission: 'finance.view',
        feature: 'finance',
      },
      {
        title: 'Invoices',
        href: '/dashboard/invoices',
        icon: Receipt,
        permission: 'finance.view',
        feature: 'invoices',
      },
      {
        title: 'Discounts',
        href: '/dashboard/discounts',
        icon: Tag,
        permission: 'finance.manage',
        feature: 'discounts',
      },
      {
        title: 'Accounting',
        href: '/dashboard/accounting',
        icon: Landmark,
        permission: 'finance.manage',
        feature: 'accounting',
      },
      {
        title: 'Expenses',
        href: '/dashboard/expenses',
        icon: Coins,
        permission: 'finance.manage',
        feature: 'expenses',
      },
      {
        title: 'Procurement',
        href: '/dashboard/procurement',
        icon: ShoppingCart,
        permission: 'finance.manage',
        feature: 'procurement',
      },
      {
        title: 'Revenue Reports',
        href: '/dashboard/revenue-reports',
        icon: DollarSign,
        permission: 'finance.view',
        feature: 'revenue-reports',
      },
      {
        title: 'Enterprise Finance',
        href: '/dashboard/enterprise-finance',
        icon: Banknote,
        permission: 'finance.manage',
        feature: 'enterprise-finance',
      },
      {
        title: 'Revenue Forecast',
        href: '/dashboard/revenue-forecast',
        icon: LineChart,
        permission: 'finance.manage',
        feature: 'revenue-forecast',
      },
    ],
  },
  {
    title: 'HR & Payroll',
    items: [
      {
        title: 'Payroll',
        href: '/dashboard/payroll',
        icon: CreditCard,
        permission: 'finance.manage',
        feature: 'payroll',
      },
      {
        title: 'Leave Management',
        href: '/dashboard/leave-management',
        icon: CalendarDays,
        permission: 'teachers.view',
        feature: 'leave-management',
      },
      {
        title: 'Employee Loans',
        href: '/dashboard/employee-loans',
        icon: Coins,
        permission: 'finance.manage',
        feature: 'employee-loans',
      },
      {
        title: 'Performance Reviews',
        href: '/dashboard/performance-reviews',
        icon: ChartBar,
        permission: 'teachers.view',
        feature: 'performance-reviews',
      },
      {
        title: 'Recruitment',
        href: '/dashboard/recruitment',
        icon: UserPlus,
        permission: 'teachers.view',
        feature: 'recruitment',
      },
      {
        title: 'Employee Contracts',
        href: '/dashboard/employee-contracts',
        icon: FileText,
        permission: 'teachers.view',
        feature: 'employee-contracts',
      },
    ],
  },
  {
    title: 'Operations',
    items: [
      {
        title: 'Library',
        href: '/dashboard/library',
        icon: BookOpenCheck,
        permission: 'settings.view',
        feature: 'library',
      },
      {
        title: 'Transport',
        href: '/dashboard/transport',
        icon: Bus,
        permission: 'settings.view',
        feature: 'transport',
      },
      {
        title: 'Transport Students',
        href: '/dashboard/transport-students',
        icon: Users,
        permission: 'settings.view',
        feature: 'transport-students',
      },
      {
        title: 'Fuel Logs',
        href: '/dashboard/fuel-logs',
        icon: Fuel,
        permission: 'settings.view',
        feature: 'fuel-logs',
      },
      {
        title: 'Vehicle Maintenance',
        href: '/dashboard/vehicle-maintenance',
        icon: Wrench,
        permission: 'settings.view',
        feature: 'vehicle-maintenance',
      },
      {
        title: 'Hostel',
        href: '/dashboard/hostel',
        icon: Home,
        permission: 'settings.view',
        feature: 'hostel',
      },
      {
        title: 'Hostel Attendance',
        href: '/dashboard/hostel-attendance',
        icon: ClipboardCheck,
        permission: 'settings.view',
        feature: 'hostel-attendance',
      },
      {
        title: 'Bed Allocations',
        href: '/dashboard/bed-allocations',
        icon: BedDouble,
        permission: 'settings.view',
        feature: 'bed-allocation',
      },
      {
        title: 'Inventory',
        href: '/dashboard/inventory',
        icon: Warehouse,
        permission: 'settings.view',
        feature: 'inventory',
      },
      {
        title: 'Suppliers',
        href: '/dashboard/suppliers',
        icon: Truck,
        permission: 'settings.view',
        feature: 'suppliers',
      },
      {
        title: 'Assets',
        href: '/dashboard/assets',
        icon: Boxes,
        permission: 'settings.view',
        feature: 'assets',
      },
    ],
  },
  {
    title: 'Academic Administration',
    items: [
      {
        title: 'Branches',
        href: '/dashboard/branches',
        icon: GitBranch,
        permission: 'settings.manage',
      },
      {
        title: 'Academic Years',
        href: '/dashboard/academic-years',
        icon: Calendar,
        permission: 'settings.manage',
      },
      {
        title: 'Academic Terms',
        href: '/dashboard/academic-terms',
        icon: CalendarClock,
        permission: 'settings.manage',
      },
    ],
  },
  {
    title: 'Communication',
    items: [
      {
        title: 'Communication',
        href: '/dashboard/communication-messages',
        icon: MessageSquare,
        permission: 'settings.manage',
        feature: 'messaging',
      },
      {
        title: 'Announcements',
        href: '/dashboard/announcements',
        icon: Megaphone,
        permission: 'settings.manage',
      },
      {
        title: 'Announcements Mgmt',
        href: '/dashboard/announcements-management',
        icon: Bell,
        permission: 'settings.manage',
        feature: 'announcements',
      },
      {
        title: 'Notification Center',
        href: '/dashboard/notification-center',
        icon: Bell,
        permission: 'settings.manage',
      },
      {
        title: 'Notification Templates',
        href: '/dashboard/notification-templates',
        icon: FileText,
        permission: 'settings.manage',
      },
      {
        title: 'Events',
        href: '/dashboard/events',
        icon: PartyPopper,
        permission: 'settings.view',
      },
      {
        title: 'Public Content',
        href: '/dashboard/public-content',
        icon: FileText,
        permission: 'settings.manage',
      },
      {
        title: 'Complaints',
        href: '/dashboard/complaints',
        icon: MessageCircle,
        permission: 'settings.manage',
        feature: 'complaints',
      },
      {
        title: 'Suggestions',
        href: '/dashboard/suggestions',
        icon: ThumbsUp,
        permission: 'settings.view',
        feature: 'suggestions',
      },
      {
        title: 'Meetings',
        href: '/dashboard/meetings',
        icon: Video,
        permission: 'settings.view',
        feature: 'meeting-scheduler',
      },
    ],
  },
  {
    title: 'Enterprise',
    items: [
      {
        title: 'Reports',
        href: '/dashboard/reports',
        icon: BarChart2,
        permission: 'settings.view',
        feature: 'reports',
      },
      {
        title: 'Analytics',
        href: '/dashboard/business-intelligence',
        icon: TrendingUp,
        permission: 'settings.view',
        feature: 'business-intelligence',
      },
      {
        title: 'Executive Dashboard',
        href: '/dashboard/executive-dashboard',
        icon: PieChart,
        permission: 'settings.view',
        feature: 'executive-dashboard',
      },
      {
        title: 'AI Learning',
        href: '/dashboard/ai-learning-assistant',
        icon: Lightbulb,
        permission: 'students.view',
        feature: 'ai-learning-assistant',
      },
      {
        title: 'AI Dashboard',
        href: '/dashboard/ai-dashboard',
        icon: Brain,
        permission: 'students.view',
        feature: 'ai-learning-assistant',
      },
      {
        title: 'BI Dashboard',
        href: '/dashboard/bi-dashboard',
        icon: LineChart,
        permission: 'settings.view',
        feature: 'performance-tracking',
      },
      {
        title: 'AI Parent Reports',
        href: '/dashboard/ai-parent-reports',
        icon: MessageSquare,
        permission: 'students.view',
        feature: 'ai-parent-reports',
      },
      {
        title: 'Risk Assessment',
        href: '/dashboard/risk-assessment',
        icon: AlertTriangle,
        permission: 'settings.manage',
        feature: 'risk-assessment',
      },
      {
        title: 'Risk Register',
        href: '/dashboard/risk-register',
        icon: AlertOctagon,
        permission: 'settings.manage',
        feature: 'risk-register',
      },
      {
        title: 'Incidents',
        href: '/dashboard/incidents',
        icon: ShieldAlert,
        permission: 'settings.manage',
        feature: 'incident-management',
      },
      {
        title: 'Performance Tracking',
        href: '/dashboard/performance-tracking',
        icon: LineChart,
        permission: 'settings.view',
        feature: 'performance-tracking',
      },
      {
        title: 'Cross-School Analytics',
        href: '/dashboard/cross-school-analytics',
        icon: BarChart2,
        permission: 'settings.view',
        feature: 'cross-school-analytics',
      },
      {
        title: 'Regional Dashboard',
        href: '/dashboard/regional-dashboard',
        icon: Building,
        permission: 'settings.view',
        feature: 'regional-dashboard',
      },
      {
        title: 'Enterprise Suite',
        href: '/dashboard/enterprise-suite',
        icon: Boxes,
        permission: 'settings.manage',
        feature: 'enterprise-suite',
      },
    ],
  },
  {
    title: 'Workflow & Automation',
    items: [
      {
        title: 'Workflow',
        href: '/dashboard/workflow',
        icon: Workflow,
        permission: 'settings.manage',
        feature: 'workflow-automation',
      },
      {
        title: 'Automation',
        href: '/dashboard/automation',
        icon: Cpu,
        permission: 'settings.manage',
        feature: 'automation-engine',
      },
      {
        title: 'Tasks',
        href: '/dashboard/tasks',
        icon: CheckSquare,
        permission: 'settings.view',
        feature: 'task-management',
      },
      {
        title: 'Tickets',
        href: '/dashboard/tickets',
        icon: Ticket,
        permission: 'settings.manage',
        feature: 'ticketing',
      },
      {
        title: 'Support Tickets',
        href: '/dashboard/support',
        icon: Ticket,
        permission: 'settings.view',
        feature: 'support',
      },
      {
        title: 'Help Center',
        href: '/dashboard/help',
        icon: HelpCircle,
        permission: 'settings.view',
        feature: 'help-center',
      },
      {
        title: 'Knowledge Base',
        href: '/dashboard/knowledge-base',
        icon: Book,
        permission: 'settings.view',
        feature: 'knowledge-base',
      },
    ],
  },
  {
    title: 'Administration',
    items: [
      {
        title: 'Activity Center',
        href: '/dashboard/activity',
        icon: Activity,
        permission: 'settings.view',
      },
      {
        title: 'Audit Logs',
        href: '/dashboard/audit',
        icon: FileCheck,
        permission: 'settings.manage',
      },
      {
        title: 'Finance Audit',
        href: '/dashboard/finance-audit',
        icon: CreditCard,
        permission: 'finance.manage',
        feature: 'finance-audit',
      },
      {
        title: 'Documents',
        href: '/dashboard/documents',
        icon: FolderOpen,
        permission: 'settings.view',
        feature: 'documents',
      },
      {
        title: 'Document Mgmt',
        href: '/dashboard/document-management',
        icon: FolderTree,
        permission: 'settings.view',
        feature: 'documents',
      },
      {
        title: 'Roles',
        href: '/dashboard/roles',
        icon: ShieldCheck,
        permission: 'settings.manage',
      },
      {
        title: 'Permissions',
        href: '/dashboard/permissions',
        icon: Lock,
        permission: 'settings.manage',
      },
      {
        title: 'Plans',
        href: '/dashboard/plans',
        icon: Package,
        permission: 'settings.view',
      },
      {
        title: 'Settings',
        href: '/dashboard/settings',
        icon: Settings,
        permission: 'settings.manage',
        feature: 'settings',
      },
      {
        title: 'Security Settings',
        href: '/dashboard/security-settings',
        icon: Shield,
        permission: 'settings.manage',
      },
      {
        title: 'Communication Settings',
        href: '/dashboard/communication-settings',
        icon: MessageSquare,
        permission: 'settings.manage',
      },
      {
        title: 'Advanced Security',
        href: '/dashboard/advanced-security',
        icon: ShieldAlert,
        permission: 'settings.manage',
        feature: 'advanced-security',
      },
      {
        title: 'API Keys',
        href: '/dashboard/api-keys',
        icon: Key,
        permission: 'settings.manage',
        feature: 'api-keys',
      },
      {
        title: 'API Platform',
        href: '/dashboard/api-platform',
        icon: Network,
        permission: 'settings.manage',
        feature: 'api-platform',
      },
      {
        title: 'Login History',
        href: '/dashboard/login-history',
        icon: Activity,
        permission: 'settings.manage',
        feature: 'login-history',
      },
      {
        title: 'IP Restrictions',
        href: '/dashboard/ip-restrictions',
        icon: ShieldCheck,
        permission: 'settings.manage',
        feature: 'ip-restrictions',
      },
      {
        title: 'Password Policies',
        href: '/dashboard/password-policies',
        icon: Lock,
        permission: 'settings.manage',
        feature: 'password-policies',
      },
      {
        title: 'System Health',
        href: '/dashboard/system-health',
        icon: Activity,
        permission: 'settings.view',
        feature: 'system-health',
      },
      {
        title: 'Backups',
        href: '/dashboard/backups',
        icon: Database,
        permission: 'settings.manage',
        feature: 'backups',
      },
      {
        title: 'Backup Mgmt',
        href: '/dashboard/backup-management',
        icon: Database,
        permission: 'settings.manage',
        feature: 'backup',
      },
      {
        title: 'Data Recovery',
        href: '/dashboard/data-recovery',
        icon: DatabaseBackup,
        permission: 'settings.manage',
        feature: 'data-recovery',
      },
      {
        title: 'White Label',
        href: '/dashboard/white-label',
        icon: Paintbrush,
        permission: 'settings.manage',
        feature: 'white-label',
      },
      {
        title: 'Dynamic Config',
        href: '/dashboard/dynamic-config',
        icon: Settings2,
        permission: 'settings.manage',
        feature: 'dynamic-config',
      },
    ],
  },
]

export const SUPER_ADMIN_NAVIGATION = [
  {
    title: 'Platform Overview',
    items: [
      {
        title: 'Overview',
        href: '/admin/dashboard',
        icon: LayoutDashboard,
      },
      {
        title: 'Schools',
        href: '/admin/schools',
        icon: School,
      },
      {
        title: 'Features',
        href: '/admin/features',
        icon: Zap,
      },
      {
        title: 'Admins',
        href: '/admin/admins',
        icon: UserCog,
      },
    ],
  },
  {
    title: 'Billing & Plans',
    items: [
      {
        title: 'Subscriptions',
        href: '/admin/subscriptions',
        icon: ClipboardList,
      },
      {
        title: 'Plans',
        href: '/admin/plans',
        icon: CreditCard,
      },
      {
        title: 'Leads',
        href: '/admin/leads',
        icon: User,
      },
    ],
  },
  {
    title: 'Operations',
    items: [
      {
        title: 'Support',
        href: '/admin/tickets',
        icon: MessageSquare,
      },
      {
        title: 'Monitoring',
        href: '/admin/errors',
        icon: ShieldAlert,
      },
      {
        title: 'System',
        href: '/admin/system',
        icon: Settings,
      },
    ],
  },
];

export const SUPER_ADMIN_BRANDING = {
  name: 'DugsiKabe Admin',
  subtitle: 'Platform Control Center',
  accent: 'text-indigo-600 dark:text-indigo-400',
  icon: Globe,
  iconGradient: 'bg-gradient-to-br from-indigo-500 to-indigo-700 shadow-indigo-500/30',
};
