import {
  LayoutDashboard,
  Users,
  UserSquare2,
  BookOpen,
  Building2,
  Calendar,
  CreditCard,
  ClipboardCheck,
  GraduationCap,
  Settings,
  Shield,
  MessageSquare,
  HelpCircle,
  Home,
  Bus,
  BookOpenCheck,
  Package,
  FileCheck,
  TrendingUp,
  BarChart2,
  Warehouse,
  CalendarDays,
  GitBranch,
  CalendarClock,
  ArrowRightLeft,
  FileSpreadsheet,
  Landmark,
  Bell,
  Megaphone,
  PartyPopper,
  FileText,
  Award,
  IdCard,
  UserPlus,
  Building,
  Wrench,
  Tag,
  Receipt,
  DollarSign,
  FileBarChart,
  FolderOpen,
  Ticket,
  ShieldCheck,
  Lock,
  Heart,
  Briefcase,
  BookMarked,
  FlaskConical,
  UserCheck,
  DoorOpen,
  Coins,
  ShoppingCart,
  Lightbulb,
  Boxes,
  Activity,
  Workflow,
  Cpu,
  Brain,
  LineChart,
  ShieldAlert,
  Network,
  Database,
  Paintbrush,
  Settings2,
  CheckSquare,
  MessageCircle,
  ThumbsUp,
  AlertTriangle,
  Book,
  Video,
  AlertOctagon,
  FolderTree,
  ChartBar,
  PieChart,
  Clock8,
  Banknote,
  Fuel,
  Truck,
  BedDouble,
  Key,
  DatabaseBackup,
  School,
  UserCog,
  ClipboardList,
  Zap,
  Globe,
} from 'lucide-react';

export const SCHOOL_NAVIGATION = [
  {
    title: null,
    items: [
      {
        title: 'Overview',
        href: '/',
        icon: LayoutDashboard,
      },
    ],
  },
  {
    title: 'Academic Management',
    items: [
      {
        title: 'Students',
        href: '/students',
        icon: Users,
        permission: 'students.view',
        feature: 'students',
      },
      {
        title: 'Admissions',
        href: '/admissions',
        icon: UserPlus,
        permission: 'students.view',
        feature: 'admissions',
      },
      {
        title: 'Teachers',
        href: '/teachers',
        icon: UserSquare2,
        permission: 'teachers.view',
        feature: 'teachers',
      },
      {
        title: 'Departments',
        href: '/departments',
        icon: Building2,
        permission: 'teachers.view',
        feature: 'departments',
      },
      {
        title: 'Designations',
        href: '/designations',
        icon: Briefcase,
        permission: 'teachers.view',
        feature: 'designations',
      },
      {
        title: 'Parents',
        href: '/parents',
        icon: Users,
        permission: 'students.view',
        feature: 'parents',
      },
      {
        title: 'Classes',
        href: '/classes',
        icon: BookOpen,
        permission: 'classes.view',
        feature: 'classes',
      },
      {
        title: 'Subjects',
        href: '/subjects',
        icon: BookOpen,
        permission: 'subjects.view',
        feature: 'subjects',
      },
      {
        title: 'Curriculum',
        href: '/curriculum',
        icon: BookMarked,
        permission: 'subjects.view',
        feature: 'curriculum',
      },
      {
        title: 'Schedule',
        href: '/schedule',
        icon: CalendarClock,
        permission: 'classes.view',
      },
      {
        title: 'Automatic Timetabling',
        href: '/automatic-timetabling',
        icon: Clock8,
        permission: 'classes.view',
        feature: 'automatic-timetabling',
      },
      {
        title: 'Attendance',
        href: '/attendance',
        icon: ClipboardCheck,
        permission: 'attendance.view',
        feature: 'attendance',
      },
      {
        title: 'Homework',
        href: '/homework',
        icon: FileText,
        permission: 'students.view',
        feature: 'homework',
      },
      {
        title: 'Lesson Plans',
        href: '/lesson-plans',
        icon: FileSpreadsheet,
        permission: 'teachers.view',
        feature: 'lesson-plans',
      },
    ],
  },
  {
    title: 'Examinations',
    items: [
      {
        title: 'Exams',
        href: '/exams',
        icon: GraduationCap,
        permission: 'exams.view',
        feature: 'exams',
      },
      {
        title: 'Online Exams',
        href: '/online-exams',
        icon: FlaskConical,
        permission: 'exams.view',
        feature: 'online-exams',
      },
      {
        title: 'Question Banks',
        href: '/question-banks',
        icon: FolderTree,
        permission: 'exams.view',
        feature: 'question-banks',
      },
      {
        title: 'Questions',
        href: '/questions',
        icon: HelpCircle,
        permission: 'exams.view',
        feature: 'question-banks',
      },
      {
        title: 'Exam Results',
        href: '/exam-results',
        icon: Award,
        permission: 'exams.view',
      },
      {
        title: 'Exam Halls',
        href: '/exam-halls',
        icon: DoorOpen,
        permission: 'exams.view',
      },
      {
        title: 'Promotions',
        href: '/promotions',
        icon: ArrowRightLeft,
        permission: 'students.view',
      },
      {
        title: 'Certificates',
        href: '/certificates',
        icon: Award,
        permission: 'exams.view',
        feature: 'certificates',
      },
      {
        title: 'ID Cards',
        href: '/id-cards',
        icon: IdCard,
        permission: 'students.view',
        feature: 'id-cards',
      },
      {
        title: 'Portfolios',
        href: '/portfolios',
        icon: FolderOpen,
        permission: 'students.view',
        feature: 'portfolios',
      },
      {
        title: 'Delivery Reports',
        href: '/delivery-reports',
        icon: FileBarChart,
        permission: 'exams.view',
        feature: 'delivery-reports',
      },
    ],
  },
  {
    title: 'Student Welfare',
    items: [
      {
        title: 'Discipline',
        href: '/discipline',
        icon: ShieldAlert,
        permission: 'students.view',
        feature: 'discipline',
      },
      {
        title: 'Health Records',
        href: '/health-records',
        icon: Heart,
        permission: 'students.view',
        feature: 'health',
      },
      {
        title: 'Alumni',
        href: '/alumni',
        icon: GraduationCap,
        permission: 'students.view',
        feature: 'alumni',
      },
      {
        title: 'Visitors',
        href: '/visitors',
        icon: UserCheck,
        permission: 'settings.view',
        feature: 'visitors',
      },
    ],
  },
  {
    title: 'Finance',
    items: [
      {
        title: 'Finance',
        href: '/payments',
        icon: CreditCard,
        permission: 'finance.view',
        feature: 'finance',
      },
      {
        title: 'Invoices',
        href: '/invoices',
        icon: Receipt,
        permission: 'finance.view',
        feature: 'invoices',
      },
      {
        title: 'Discounts',
        href: '/discounts',
        icon: Tag,
        permission: 'finance.manage',
        feature: 'discounts',
      },
      {
        title: 'Accounting',
        href: '/accounting',
        icon: Landmark,
        permission: 'finance.manage',
        feature: 'accounting',
      },
      {
        title: 'Expenses',
        href: '/expenses',
        icon: Coins,
        permission: 'finance.manage',
        feature: 'expenses',
      },
      {
        title: 'Procurement',
        href: '/procurement',
        icon: ShoppingCart,
        permission: 'finance.manage',
        feature: 'procurement',
      },
      {
        title: 'Revenue Reports',
        href: '/revenue-reports',
        icon: DollarSign,
        permission: 'finance.view',
        feature: 'revenue-reports',
      },
      {
        title: 'Enterprise Finance',
        href: '/enterprise-finance',
        icon: Banknote,
        permission: 'finance.manage',
        feature: 'enterprise-finance',
      },
      {
        title: 'Revenue Forecast',
        href: '/revenue-forecast',
        icon: LineChart,
        permission: 'finance.manage',
        feature: 'revenue-forecast',
      },
    ],
  },
  {
    title: 'HR & Payroll',
    items: [
      {
        title: 'Payroll',
        href: '/payroll',
        icon: CreditCard,
        permission: 'finance.manage',
        feature: 'payroll',
      },
      {
        title: 'Leave Management',
        href: '/leave-management',
        icon: CalendarDays,
        permission: 'teachers.view',
        feature: 'leave-management',
      },
      {
        title: 'Employee Loans',
        href: '/employee-loans',
        icon: Coins,
        permission: 'finance.manage',
        feature: 'employee-loans',
      },
      {
        title: 'Performance Reviews',
        href: '/performance-reviews',
        icon: ChartBar,
        permission: 'teachers.view',
        feature: 'performance-reviews',
      },
      {
        title: 'Recruitment',
        href: '/recruitment',
        icon: UserPlus,
        permission: 'teachers.view',
        feature: 'recruitment',
      },
      {
        title: 'Employee Contracts',
        href: '/employee-contracts',
        icon: FileText,
        permission: 'teachers.view',
        feature: 'employee-contracts',
      },
    ],
  },
  {
    title: 'Operations',
    items: [
      {
        title: 'Library',
        href: '/library',
        icon: BookOpenCheck,
        permission: 'settings.view',
        feature: 'library',
      },
      {
        title: 'Transport',
        href: '/transport',
        icon: Bus,
        permission: 'settings.view',
        feature: 'transport',
      },
      {
        title: 'Transport Students',
        href: '/transport-students',
        icon: Users,
        permission: 'settings.view',
        feature: 'transport-students',
      },
      {
        title: 'Fuel Logs',
        href: '/fuel-logs',
        icon: Fuel,
        permission: 'settings.view',
        feature: 'fuel-logs',
      },
      {
        title: 'Vehicle Maintenance',
        href: '/vehicle-maintenance',
        icon: Wrench,
        permission: 'settings.view',
        feature: 'vehicle-maintenance',
      },
      {
        title: 'Hostel',
        href: '/hostel',
        icon: Home,
        permission: 'settings.view',
        feature: 'hostel',
      },
      {
        title: 'Hostel Attendance',
        href: '/hostel-attendance',
        icon: ClipboardCheck,
        permission: 'settings.view',
        feature: 'hostel-attendance',
      },
      {
        title: 'Bed Allocations',
        href: '/bed-allocations',
        icon: BedDouble,
        permission: 'settings.view',
        feature: 'bed-allocation',
      },
      {
        title: 'Inventory',
        href: '/inventory',
        icon: Warehouse,
        permission: 'settings.view',
        feature: 'inventory',
      },
      {
        title: 'Suppliers',
        href: '/suppliers',
        icon: Truck,
        permission: 'settings.view',
        feature: 'suppliers',
      },
      {
        title: 'Assets',
        href: '/assets',
        icon: Boxes,
        permission: 'settings.view',
        feature: 'assets',
      },
    ],
  },
  {
    title: 'Academic Administration',
    items: [
      {
        title: 'Branches',
        href: '/branches',
        icon: GitBranch,
        permission: 'settings.manage',
      },
      {
        title: 'Academic Years',
        href: '/academic-years',
        icon: Calendar,
        permission: 'settings.manage',
      },
      {
        title: 'Academic Terms',
        href: '/academic-terms',
        icon: CalendarClock,
        permission: 'settings.manage',
      },
    ],
  },
  {
    title: 'Communication',
    items: [
      {
        title: 'Communication',
        href: '/communication-messages',
        icon: MessageSquare,
        permission: 'settings.manage',
        feature: 'messaging',
      },
      {
        title: 'Announcements',
        href: '/announcements',
        icon: Megaphone,
        permission: 'settings.manage',
      },
      {
        title: 'Announcements Mgmt',
        href: '/announcements-management',
        icon: Bell,
        permission: 'settings.manage',
        feature: 'announcements',
      },
      {
        title: 'Notification Center',
        href: '/notification-center',
        icon: Bell,
        permission: 'settings.manage',
      },
      {
        title: 'Notification Templates',
        href: '/notification-templates',
        icon: FileText,
        permission: 'settings.manage',
      },
      {
        title: 'Events',
        href: '/events',
        icon: PartyPopper,
        permission: 'settings.view',
      },
      {
        title: 'Public Content',
        href: '/public-content',
        icon: FileText,
        permission: 'settings.manage',
      },
      {
        title: 'Complaints',
        href: '/complaints',
        icon: MessageCircle,
        permission: 'settings.manage',
        feature: 'complaints',
      },
      {
        title: 'Suggestions',
        href: '/suggestions',
        icon: ThumbsUp,
        permission: 'settings.view',
        feature: 'suggestions',
      },
      {
        title: 'Meetings',
        href: '/meetings',
        icon: Video,
        permission: 'settings.view',
        feature: 'meeting-scheduler',
      },
    ],
  },
  {
    title: 'Enterprise',
    items: [
      {
        title: 'Reports',
        href: '/reports',
        icon: BarChart2,
        permission: 'settings.view',
        feature: 'reports',
      },
      {
        title: 'Analytics',
        href: '/business-intelligence',
        icon: TrendingUp,
        permission: 'settings.view',
        feature: 'business-intelligence',
      },
      {
        title: 'Executive Dashboard',
        href: '/executive-dashboard',
        icon: PieChart,
        permission: 'settings.view',
        feature: 'executive-dashboard',
      },
      {
        title: 'AI Learning',
        href: '/ai-learning-assistant',
        icon: Lightbulb,
        permission: 'students.view',
        feature: 'ai-learning-assistant',
      },
      {
        title: 'AI Dashboard',
        href: '/ai-dashboard',
        icon: Brain,
        permission: 'students.view',
        feature: 'ai-learning-assistant',
      },
      {
        title: 'BI Dashboard',
        href: '/bi-dashboard',
        icon: LineChart,
        permission: 'settings.view',
        feature: 'performance-tracking',
      },
      {
        title: 'AI Parent Reports',
        href: '/ai-parent-reports',
        icon: MessageSquare,
        permission: 'students.view',
        feature: 'ai-parent-reports',
      },
      {
        title: 'Risk Assessment',
        href: '/risk-assessment',
        icon: AlertTriangle,
        permission: 'settings.manage',
        feature: 'risk-assessment',
      },
      {
        title: 'Risk Register',
        href: '/risk-register',
        icon: AlertOctagon,
        permission: 'settings.manage',
        feature: 'risk-register',
      },
      {
        title: 'Incidents',
        href: '/incidents',
        icon: ShieldAlert,
        permission: 'settings.manage',
        feature: 'incident-management',
      },
      {
        title: 'Performance Tracking',
        href: '/performance-tracking',
        icon: LineChart,
        permission: 'settings.view',
        feature: 'performance-tracking',
      },
      {
        title: 'Cross-School Analytics',
        href: '/cross-school-analytics',
        icon: BarChart2,
        permission: 'settings.view',
        feature: 'cross-school-analytics',
      },
      {
        title: 'Regional Dashboard',
        href: '/regional-dashboard',
        icon: Building,
        permission: 'settings.view',
        feature: 'regional-dashboard',
      },
      {
        title: 'Enterprise Suite',
        href: '/enterprise-suite',
        icon: Boxes,
        permission: 'settings.manage',
        feature: 'enterprise-suite',
      },
    ],
  },
  {
    title: 'Workflow & Automation',
    items: [
      {
        title: 'Workflow',
        href: '/workflow',
        icon: Workflow,
        permission: 'settings.manage',
        feature: 'workflow-automation',
      },
      {
        title: 'Automation',
        href: '/automation',
        icon: Cpu,
        permission: 'settings.manage',
        feature: 'automation-engine',
      },
      {
        title: 'Tasks',
        href: '/tasks',
        icon: CheckSquare,
        permission: 'settings.view',
        feature: 'task-management',
      },
      {
        title: 'Tickets',
        href: '/tickets',
        icon: Ticket,
        permission: 'settings.manage',
        feature: 'ticketing',
      },
      {
        title: 'Support Tickets',
        href: '/support',
        icon: Ticket,
        permission: 'settings.view',
        feature: 'support',
      },
      {
        title: 'Help Center',
        href: '/help',
        icon: HelpCircle,
        permission: 'settings.view',
        feature: 'help-center',
      },
      {
        title: 'Knowledge Base',
        href: '/knowledge-base',
        icon: Book,
        permission: 'settings.view',
        feature: 'knowledge-base',
      },
    ],
  },
  {
    title: 'Administration',
    items: [
      {
        title: 'Activity Center',
        href: '/activity',
        icon: Activity,
        permission: 'settings.view',
      },
      {
        title: 'Audit Logs',
        href: '/audit',
        icon: FileCheck,
        permission: 'settings.manage',
      },
      {
        title: 'Finance Audit',
        href: '/finance-audit',
        icon: CreditCard,
        permission: 'finance.manage',
        feature: 'finance-audit',
      },
      {
        title: 'Documents',
        href: '/documents',
        icon: FolderOpen,
        permission: 'settings.view',
        feature: 'documents',
      },
      {
        title: 'Document Mgmt',
        href: '/document-management',
        icon: FolderTree,
        permission: 'settings.view',
        feature: 'documents',
      },
      {
        title: 'Roles',
        href: '/roles',
        icon: ShieldCheck,
        permission: 'settings.manage',
      },
      {
        title: 'Permissions',
        href: '/permissions',
        icon: Lock,
        permission: 'settings.manage',
      },
      {
        title: 'Plans',
        href: '/plans',
        icon: Package,
        permission: 'settings.view',
      },
      {
        title: 'Settings',
        href: '/settings',
        icon: Settings,
        permission: 'settings.manage',
        feature: 'settings',
      },
      {
        title: 'Security Settings',
        href: '/security-settings',
        icon: Shield,
        permission: 'settings.manage',
      },
      {
        title: 'Communication Settings',
        href: '/communication-settings',
        icon: MessageSquare,
        permission: 'settings.manage',
      },
      {
        title: 'Advanced Security',
        href: '/advanced-security',
        icon: ShieldAlert,
        permission: 'settings.manage',
        feature: 'advanced-security',
      },
      {
        title: 'API Keys',
        href: '/api-keys',
        icon: Key,
        permission: 'settings.manage',
        feature: 'api-keys',
      },
      {
        title: 'API Platform',
        href: '/api-platform',
        icon: Network,
        permission: 'settings.manage',
        feature: 'api-platform',
      },
      {
        title: 'Login History',
        href: '/login-history',
        icon: Activity,
        permission: 'settings.manage',
        feature: 'login-history',
      },
      {
        title: 'IP Restrictions',
        href: '/ip-restrictions',
        icon: ShieldCheck,
        permission: 'settings.manage',
        feature: 'ip-restrictions',
      },
      {
        title: 'Password Policies',
        href: '/password-policies',
        icon: Lock,
        permission: 'settings.manage',
        feature: 'password-policies',
      },
      {
        title: 'System Health',
        href: '/system-health',
        icon: Activity,
        permission: 'settings.view',
        feature: 'system-health',
      },
      {
        title: 'Backups',
        href: '/backups',
        icon: Database,
        permission: 'settings.manage',
        feature: 'backups',
      },
      {
        title: 'Backup Mgmt',
        href: '/backup-management',
        icon: Database,
        permission: 'settings.manage',
        feature: 'backup',
      },
      {
        title: 'Data Recovery',
        href: '/data-recovery',
        icon: DatabaseBackup,
        permission: 'settings.manage',
        feature: 'data-recovery',
      },
      {
        title: 'White Label',
        href: '/white-label',
        icon: Paintbrush,
        permission: 'settings.manage',
        feature: 'white-label',
      },
      {
        title: 'Dynamic Config',
        href: '/dynamic-config',
        icon: Settings2,
        permission: 'settings.manage',
        feature: 'dynamic-config',
      },
    ],
  },
];

export const SUPER_ADMIN_NAVIGATION = [
  {
    title: 'Platform Overview',
    items: [
      {
        title: 'Overview',
        href: '/admin',
        icon: LayoutDashboard,
      },
      {
        title: 'Schools',
        href: '/admin/schools',
        icon: School,
      },
      {
        title: 'Features',
        href: '/admin/features',
        icon: Zap,
      },
      {
        title: 'Admins',
        href: '/admin/admins',
        icon: UserCog,
      },
    ],
  },
  {
    title: 'Billing & Plans',
    items: [
      {
        title: 'Subscriptions',
        href: '/admin/subscriptions',
        icon: ClipboardList,
      },
      {
        title: 'Plans',
        href: '/admin/plans',
        icon: CreditCard,
      },
      {
        title: 'Leads',
        href: '/admin/leads',
        icon: Users,
      },
    ],
  },
  {
    title: 'Operations',
    items: [
      {
        title: 'Support',
        href: '/admin/tickets',
        icon: MessageSquare,
      },
      {
        title: 'Monitoring',
        href: '/admin/errors',
        icon: ShieldAlert,
      },
      {
        title: 'System',
        href: '/admin/system',
        icon: Settings,
      },
    ],
  },
];

export const SUPER_ADMIN_BRANDING = {
  name: 'DugsiKabe Admin',
  subtitle: 'Platform Control Center',
  accent: 'text-indigo-600 dark:text-indigo-400',
  icon: Globe,
  iconGradient: 'bg-gradient-to-br from-indigo-500 to-indigo-700 shadow-indigo-500/30',
};
